# Entrenamiento de una Neurona

In [1]:
# Importar librerias
import numpy as np
from numpy import exp, array, random, dot, tanh 
import matplotlib.pyplot as plt


In [2]:
# Clase para crear la red neuronal
# De una sola neurona
class NeuralNetwork(): 
      
    def __init__(self): 
          
        # Utilizar seed para 
        # configurar los mismos valores siempre
        random.seed(1) 
        self.records = np.arange(1)
        # Definir matriz de pesos 
        self.weight_matrix = 2 * random.random((3, 1)) - 1
  
    # Funcion de activación
    def tanh(self, x): 
        return tanh(x) 
  
    # Derivada de la funcion de activación
    # Para calcular gradientes.
    def tanh_derivative(self, x): 
        return 1.0 - tanh(x) ** 2
  
    # Propagacion hacia adelante
    # Aqui se ingresan los datos 
    # y se obtienen las predicciones
    def forward_propagation(self, inputs): 
        return self.tanh(dot(inputs, self.weight_matrix)) 
      
    # Definicion del entrenamiento. 
    def train(self, train_inputs, train_outputs, 
                            num_train_iterations): 
                                  
        # Numero de veces que queremos 
        # realizar el proceso de entrenamiento. 
        for iteration in range(num_train_iterations): 
            output = self.forward_propagation(train_inputs) 
  
            # Calcular el error en la salida.
            error = train_outputs - output 
            self.records
            # multiply the error by input and then  
            # by gradient of tanh funtion to calculate 
            # the adjustment needs to be made in weights 
            adjustment = dot(train_inputs.T, error *
                             self.tanh_derivative(output)) 
                               
            # Adjust the weight matrix 
            self.weight_matrix += adjustment 


In [3]:
x = np.arange(0,4*np.pi,0.1)   # start,stop,step
y = np.sin(x)

train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]]) 
train_outputs = array([[0, 1, 1, 0]]).T 

print('Entradas:')
print(train_inputs)
print('Salidas:')
print(train_outputs)


Entradas:
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
Salidas:
[[0]
 [1]
 [1]
 [0]]


In [4]:
neural_network = NeuralNetwork() 
print ('Pesos antes del entrenamiento:') 
print (neural_network.weight_matrix) 
print("Red neuronal no entrenada:")
print (neural_network.forward_propagation(array([0, 0, 1]))) 
print (neural_network.forward_propagation(array([1, 1, 1]))) 
print (neural_network.forward_propagation(array([1, 0, 1]))) 
print (neural_network.forward_propagation(array([0, 1, 1]))) 


Pesos antes del entrenamiento:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Red neuronal no entrenada:
[-0.76149807]
[-0.62004504]
[-0.8228976]
[-0.5073259]


In [5]:
neural_network.train(train_inputs, train_outputs, 50000) 

print ('Pesos despues del entrenamiento:') 
print (neural_network.weight_matrix) 

print("Red neuronal entrenada:")
print (neural_network.forward_propagation(array([0, 0, 1]))) 
print (neural_network.forward_propagation(array([1, 1, 1]))) 
print (neural_network.forward_propagation(array([1, 0, 1]))) 
print (neural_network.forward_propagation(array([0, 1, 1]))) 


Pesos despues del entrenamiento:
[[6.19852837]
 [0.1947659 ]
 [0.34311074]]
Red neuronal entrenada:
[0.3302517]
[0.99999718]
[0.99999584]
[0.49137898]
